// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ceedee.proto

package ceedeeproto

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Directory struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Directory) Reset()         { *m = Directory{} }
func (m *Directory) String() string { return proto.CompactTextString(m) }
func (*Directory) ProtoMessage()    {}
func (*Directory) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6621867960c145, []int{0}
}

func (m *Directory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Directory.Unmarshal(m, b)
}
func (m *Directory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Directory.Marshal(b, m, deterministic)
}
func (m *Directory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Directory.Merge(m, src)
}
func (m *Directory) XXX_Size() int {
	return xxx_messageInfo_Directory.Size(m)
}
func (m *Directory) XXX_DiscardUnknown() {
	xxx_messageInfo_Directory.DiscardUnknown(m)
}

var xxx_messageInfo_Directory proto.InternalMessageInfo

func (m *Directory) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Dlist struct {
	Dirs                 string   `protobuf:"bytes,1,opt,name=dirs,proto3" json:"dirs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dlist) Reset()         { *m = Dlist{} }
func (m *Dlist) String() string { return proto.CompactTextString(m) }
func (*Dlist) ProtoMessage()    {}
func (*Dlist) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6621867960c145, []int{1}
}

func (m *Dlist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dlist.Unmarshal(m, b)
}
func (m *Dlist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dlist.Marshal(b, m, deterministic)
}
func (m *Dlist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dlist.Merge(m, src)
}
func (m *Dlist) XXX_Size() int {
	return xxx_messageInfo_Dlist.Size(m)
}
func (m *Dlist) XXX_DiscardUnknown() {
	xxx_messageInfo_Dlist.DiscardUnknown(m)
}

var xxx_messageInfo_Dlist proto.InternalMessageInfo

func (m *Dlist) GetDirs() string {
	if m != nil {
		return m.Dirs
	}
	return ""
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6621867960c145, []int{2}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Directory)(nil), "ceedeeproto.Directory")
	proto.RegisterType((*Dlist)(nil), "ceedeeproto.Dlist")
	proto.RegisterType((*Void)(nil), "ceedeeproto.Void")
}

func init() { proto.RegisterFile("ceedee.proto", fileDescriptor_db6621867960c145) }

var fileDescriptor_db6621867960c145 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x4e, 0x4d, 0x4d,
	0x49, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x86, 0xf0, 0xc0, 0x1c, 0x25, 0x79,
	0x2e, 0x4e, 0x97, 0xcc, 0xa2, 0xd4, 0xe4, 0x92, 0xfc, 0xa2, 0x4a, 0x21, 0x21, 0x2e, 0x96, 0xbc,
	0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x49, 0x9a, 0x8b, 0xd5,
	0x25, 0x27, 0xb3, 0xb8, 0x04, 0x24, 0x99, 0x92, 0x59, 0x54, 0x0c, 0x93, 0x04, 0xb1, 0x95, 0xd8,
	0xb8, 0x58, 0xc2, 0xf2, 0x33, 0x53, 0x8c, 0x6c, 0xb9, 0xd8, 0x9c, 0x53, 0x53, 0x5d, 0x52, 0x53,
	0x85, 0x8c, 0xb9, 0x98, 0xdd, 0x53, 0x4b, 0x84, 0xc4, 0xf4, 0x90, 0x2c, 0xd1, 0x83, 0xdb, 0x20,
	0x25, 0x84, 0x2a, 0x0e, 0x32, 0x58, 0x89, 0x21, 0x89, 0x0d, 0xcc, 0x35, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xfe, 0xc8, 0xff, 0xb7, 0xa8, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CeeDeeClient is the client API for CeeDee service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CeeDeeClient interface {
	Get(ctx context.Context, in *Directory, opts ...grpc.CallOption) (*Dlist, error)
}

type ceeDeeClient struct {
	cc *grpc.ClientConn
}

func NewCeeDeeClient(cc *grpc.ClientConn) CeeDeeClient {
	return &ceeDeeClient{cc}
}

func (c *ceeDeeClient) Get(ctx context.Context, in *Directory, opts ...grpc.CallOption) (*Dlist, error) {
	out := new(Dlist)
	err := c.cc.Invoke(ctx, "/ceedeeproto.CeeDee/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CeeDeeServer is the server API for CeeDee service.
type CeeDeeServer interface {
	Get(context.Context, *Directory) (*Dlist, error)
}

func RegisterCeeDeeServer(s *grpc.Server, srv CeeDeeServer) {
	s.RegisterService(&_CeeDee_serviceDesc, srv)
}

func _CeeDee_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Directory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CeeDeeServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ceedeeproto.CeeDee/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CeeDeeServer).Get(ctx, req.(*Directory))
	}
	return interceptor(ctx, in, info, handler)
}

var _CeeDee_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ceedeeproto.CeeDee",
	HandlerType: (*CeeDeeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _CeeDee_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ceedee.proto",
}
